version: 2
updates:
  # Github Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "04:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 15
    target-branch: dev
    reviewers:
      - marcauberer
    assignees:
      - marcauberer
  
  # Dockerfile - amd64
  - package-ecosystem: docker
    directory: /amd64
    schedule:
      interval: daily
      time: "04:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 15
    target-branch: dev
    reviewers:
      - marcauberer
    assignees:
      - marcauberer

  # Dockerfile - i386
  - package-ecosystem: docker
    directory: /i386
    schedule:
      interval: daily
      time: "04:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 15
    target-branch: dev
    reviewers:
      - marcauberer
    assignees:
      - marcauberer

  # Dockerfile - armv6
  - package-ecosystem: docker
    directory: /armv6
    schedule:
      interval: daily
      time: "04:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 15
    target-branch: dev
    reviewers:
      - marcauberer
    assignees:
      - marcauberer

  # Dockerfile - armv7
  - package-ecosystem: docker
    directory: /armv7
    schedule:
      interval: daily
      time: "04:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 15
    target-branch: dev
    reviewers:
      - marcauberer
    assignees:
      - marcauberer

  # Dockerfile - arm64
  - package-ecosystem: docker
    directory: /arm64
    schedule:
      interval: daily
      time: "04:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 15
    target-branch: dev
    reviewers:
      - marcauberer
    assignees:
      - marcauberer
