# Publish Dev
name: Publish Dev

on:
  push:
    branches: [ main, dev ]
#    paths:
#      - 'Dockerfile'

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - {
              dir: amd64,
              docker-arch: linux/amd64
            }
          - {
              dir: i386,
              docker-arch: linux/i386
            }
          - {
              dir: armv6,
              docker-arch: linux/arm/v6
            }
          - {
              dir: armv7,
              docker-arch: linux/arm/v7
            }
          - {
              dir: arm64,
              docker-arch: linux/arm64/v8
            }
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker login GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Docker login Docker Hub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: chillibits
          password: ${{ secrets.DOCKER_HUB_SECRET }}
          
      - name: Build Docker image and push to registries
        working-directory: ./${{ matrix.arch.dir }}
        run: docker buildx build --push --platform ${{ matrix.arch.docker-arch }} -t ghcr.io/compose-generator/compose-generator-toolbox:dev -t chillibits/compose-generator-toolbox:dev .
