# Publish

name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Get version name
        id: get_version
        uses: battila7/get-version-action@v2
        
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker login GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Docker login Docker Hub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: chillibits
          password: ${{ secrets.DOCKER_HUB_SECRET }}

      - name: Build Docker image and push to registries # ToDo: ,linux/i386,linux/arm/v5,linux/arm/v6,linux/arm/v7,linux/arm64/v8
        run: docker buildx build --push --platform linux/amd64 -t ghcr.io/compose-generator/compose-generator-toolbox:latest \
          -t ghcr.io/compose-generator/compose-generator-toolbox:${{ steps.get_version.outputs.version }} \
          -t chillibits/compose-generator-toolbox:latest -t chillibits/compose-generator-toolbox:${{ steps.get_version.outputs.version }} .