# Dockerfile Validation
name: Dockerfile Validation

on:
  push:
#    paths:
#      - './amd64/Dockerfile'
#      - './i386/Dockerfile'
#      - './armv6/Dockerfile'
#      - './armv7/Dockerfile'
#      - './arm64/Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint Dockerfile (amd64)
        run: docker run --rm -i hadolint/hadolint < ./amd64/Dockerfile

      - name: Lint Dockerfile (i386)
        run: docker run --rm -i hadolint/hadolint < ./i386/Dockerfile

      - name: Lint Dockerfile (armv6)
        run: docker run --rm -i hadolint/hadolint < ./armv6/Dockerfile

      - name: Lint Dockerfile (armv7)
        run: docker run --rm -i hadolint/hadolint < ./armv7/Dockerfile

      - name: Lint Dockerfile (arm64)
        run: docker run --rm -i hadolint/hadolint < ./arm64/Dockerfile